<?php
/** @var Amasty\CoolModule\Block\Index $block */

?>

<form>
    <fieldset>
        <legend>Поиск</legend>
        <p><label>Введите sku </label><input type="text" name="sku"></p>
        <p><label>Введите qty</label><input type="number" name="qty"></p>
    </fieldset>
    <div>
        <h3><?= $block->getChildHtml(); ?></h3>
    </div>
    <p><input class="button" id="button" type="submit" value="Кнопка"></p>
</form>



