<?php

/** @var Amasty\CoolModule\Block\Index $block */

$cssClassForm = $this->hasCssClassForm() ? ' ' . $this->getCssClassForm() : '';
?>

<form class="<?= $cssClassForm ?>">
        <fieldset>
        <legend>Поиск</legend>
        <p><label>Введите sku </label><input type="text" name="sku"></p>
            <?php if($block->qtyDisplay()): ?>
        <p><label>Введите qty</label><input type="number" value='<?=$block->inDefaultQty()?>' name="qty"></p>
        <?php endif;?>
    </fieldset>
    <div>
        <h3><?= $block->getChildHtml(); ?></h3>
    </div>
    <input class="button" type="submit" value="Кнопка">
</form>



